### ISSUE TITLE
Not an issue but looking for how to use these indicators

### ISSUE THREAD

**Issue by snrsamy** [goxr3plus/TradingView_GoldenIndicator#2]
Please advise if there is a write-up on how to use this indicator

**Comment by goxr3plus** [comment]
Hello :) . Well you have to go on trading view , copy and paste the code on the pine editor 

https://www.youtube.com/watch?v=YRhmXmTB2RI

On the part of how to use it's a little complicated . You need trading knowledge . Start by learning basic trading indicators like moving average , rsi etc . And start trading with demo accounts for example on [icmarkets](https://www.icmarkets.com/global/en/) etc

**Comment by snrsamy** [comment]
Thanks a bunch
